import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PokemonListRootProvider } from "./contexts/usePokemonListContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pokedex Next.js",
  description: "Generated by create next app",
  icons: {
    icon: "https://www.svgrepo.com/show/276264/pokeball-pokemon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PokemonListRootProvider>
          {children}
        </PokemonListRootProvider>
      </body>
    </html>
  );
}
